plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.coreservice'
    compileSdk 31
    
    defaultConfig {
        applicationId "com.example.coreservice"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"
    }
    
    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    packagingOptions {
        exclude 'META-INF/proguard/androidx-*.pro'
        exclude 'META-INF/CHANGES'
    }
    
    lintOptions {
        disable 'MissingDimensionality'
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
}
